wp:
  name: wp-app
  labels:
    id: c0905659
    app: wp
    env: dev
  image:
    repository: wordpress
    tag: latest
    pullPolicy: Always
  replicas: 3
  configmap:
    ## KEY: "value"
    APP_ENV: "dev"
    WORDPRESS_DB_HOST: "wp-database.db.svc.cluster.local"
    WORDPRESS_DB_NAME: "wordpress"
    WORDPRESS_DB_USER: "wordpress"
  containerPorts:
      http: 80
