apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    id: {{ .Values.labels.id }}
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      id: {{ .Values.labels.id }}
      app: {{ .Values.labels.app }}
      env: {{ .Values.labels.env }}
  template:
    metadata:
      labels:
        id: {{ .Values.labels.id }}
        app: {{ .Values.labels.app }}
        env: {{ .Values.labels.env }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Values.configMap.name }}
